// skill-data.js — Static lookup tables for Hexa Order
// Update this file when new classes or skills are added.

// ── Class name map: English → Korean (for API query) ──────────────────────
var CLASS_MAP = {
  "Hero":"히어로","Paladin":"팔라딘","Dark Knight":"다크나이트",
  "Arch Mage (Fire/Poison)":"아크메이지(불,독)","Arch Mage (Ice/Lightning)":"아크메이지(썬,콜)","Bishop":"비숍",
  "Bow Master":"보우마스터","Marksman":"신궁","Pathfinder":"패스파인더",
  "Night Lord":"나이트로드","Shadower":"섀도어","Dual Blade":"듀얼블레이드",
  "Buccaneer":"바이퍼","Corsair":"캡틴","Cannoneer":"캐논슈터",
  "Dawn Warrior":"소울마스터","Blaze Wizard":"플레임위자드","Wind Archer":"윈드브레이커",
  "Night Walker":"나이트워커","Thunder Breaker":"스트라이커","Mihile":"미하일",
  "Aran":"아란","Evan":"에반","Mercedes":"메르세데스","Phantom":"팬텀",
  "Luminous":"루미너스","Shade":"은월",
  "Blaster":"블래스터","Battle Mage":"배틀메이지","Wild Hunter":"와일드헌터",
  "Mechanic":"메카닉","Xenon":"제논",
  "Demon Slayer":"데몬슬레이어","Demon Avenger":"데몬어벤져",
  "Kaiser":"카이저","Kain":"카인","Cadena":"카데나","Angelic Buster":"엔젤릭버스터",
  "Zero":"제로","Kinesis":"키네시스",
  "Adele":"아델","Illium":"일리움","Ark":"아크",
  "Hoyoung":"호영","Lara":"라라","Khali":"칼리","Ren":"렌"
};

// ── Mastery slot labels ───────────────────────────────────────────────────
// ID 2 = Mastery 1, IDs 7-9 = Masteries 2-4
var MASTERY_LABEL = { 2:'M1', 7:'M2', 8:'M3', 9:'M4' };

// ── Image filename → English skill name ───────────────────────────────────
// Key format: ClassName_ID  e.g. "Phantom_2" -> "HEXA Tempest"
// IDs: 1=Origin, 2=Mastery1, 3-6=Enhancements 1-4, 7-9=Masteries 2-4, 10=Ascent
// Classes not yet mapped: Kanna, Hayato, Mo Xuan, Sia Astelle, Lynn
var IMG_NAMES = {
  'Adele_1':'Maestro',
  'Adele_10':'Einheit',
  'Adele_2':'HEXA Cleave',
  'Adele_3':'Ruin',
  'Adele_4':'Infinity Blade',
  'Adele_5':'Legacy Restoration',
  'Adele_6':'Storm',
  'Adele_7':'HEXA Hunting Decree',
  'Adele_8':'HEXA Impale',
  'Adele_9':'HEXA Aether Forge',
  'AngelicBuster_1':'Grand Finale',
  'AngelicBuster_10':'Genuine Encore',
  'AngelicBuster_2':'HEXA Trinity',
  'AngelicBuster_3':'Sparkle Burst',
  'AngelicBuster_4':'Superstar Spotlight',
  'AngelicBuster_5':'Mighty Mascot',
  'AngelicBuster_6':'Trinity Fusion',
  'AngelicBuster_7':'HEXA Soul Seeker',
  'AngelicBuster_8':'HEXA Supreme Supernova',
  'AngelicBuster_9':'HEXA Celestial Roar',
  'Aran_1':'Endgame',
  'Aran_10':'Frost Bluster',
  'Aran_2':'HEXA Beyond Blade',
  'Aran_3':'Finisher - Adrenaline Surge',
  'Aran_4':'Maha\'s Carnage',
  'Aran_5':'Final Beyond Blade - White Tiger',
  'Aran_6':'Blizzard Tempest',
  'Aran_7':'HEXA Finisher - Hunter\'s Prey',
  'Aran_8':'HEXA Hyper Finisher - Last Stand',
  'Aran_9':'HEXA Permafrost',
  'ArchMageFP_1':'Infernal Venom',
  'ArchMageFP_10':'Torrential Flame',
  'ArchMageFP_2':'HEXA Flame Sweep',
  'ArchMageFP_3':'DoT Punisher',
  'ArchMageFP_4':'Poison Nova',
  'ArchMageFP_5':'Elemental Fury',
  'ArchMageFP_6':'Poison Chain',
  'ArchMageFP_7':'HEXA Flame Haze',
  'ArchMageFP_8':'HEXA Ignite',
  'ArchMageFP_9':'HEXA Creeping Toxin',
  'ArchMageTC_1':'Frozen Lightning',
  'ArchMageTC_10':'Parabolic Volt',
  'ArchMageTC_2':'HEXA Chain Lightning',
  'ArchMageTC_3':'Ice Age',
  'ArchMageTC_4':'Bolt Barrage',
  'ArchMageTC_5':'Spirit of Snow',
  'ArchMageTC_6':'Jupiter Thunder',
  'ArchMageTC_7':'HEXA Frozen Orb',
  'ArchMageTC_8':'HEXA Lightning Orb',
  'ArchMageTC_9':'HEXA Thunder Sphere',
  'Ark_1':'Primordial Abyss',
  'Ark_10':'Whisper of the Absolute Abyss',
  'Ark_2':'HEXA Basic Charge Drive',
  'Ark_3':'Abyssal Recall',
  'Ark_4':'Infinity Spell',
  'Ark_5':'Devious Nightmare/Devious Dream',
  'Ark_6':'Endlessly Starving Beast',
  'Ark_7':'HEXA Grevious Wound',
  'Ark_8':'HEXA Vengeful Hate',
  'Ark_9':'HEXA Ominous Nightmare',
  'BattleMage_1':'Crimson Pact',
  'BattleMage_10':'Gloomy Aura',
  'BattleMage_2':'HEXA Condemnation',
  'BattleMage_3':'Aura Scythe',
  'BattleMage_4':'Altar of Annihilation',
  'BattleMage_5':'Grim Harvest',
  'BattleMage_6':'Abyssal Lightning',
  'BattleMage_7':'HEXA Finishing Blow',
  'BattleMage_8':'HEXA Dark Shock',
  'BattleMage_9':'HEXA Dark Genesis',
  'Bishop_1':'Holy Advent',
  'Bishop_10':'Command of Heaven',
  'Bishop_2':'HEXA Angel Ray',
  'Bishop_3':'Benediction',
  'Bishop_4':'Angel of Balance',
  'Bishop_5':'Peacemaker',
  'Bishop_6':'Divine Punishment',
  'Bishop_7':'HEXA Big Bang',
  'Bishop_8':'HEXA Angelic Wrath',
  'Bishop_9':'HEXA Genesis',
  'Blaster_1':'Final Destroyer',
  'Blaster_10':'Vanguard Impact',
  'Blaster_2':'HEXA Magnum Punch',
  'Blaster_3':'Rocket Punch',
  'Blaster_4':'Gatling Punch',
  'Blaster_5':'Bullet Blast',
  'Blaster_6':'Afterimage Shock',
  'Blaster_7':'HEXA Bunker Buster Explosion',
  'Blaster_8':'HEXA Revolving Cannon Mastery',
  'Blaster_9':'HEXA Revovling Cannon',
  'FlameWizard_1':'Eternity',
  'FlameWizard_10':'Flame Concerto',
  'FlameWizard_2':'HEXA Orbital Flame',
  'FlameWizard_3':'Orbital Inferno',
  'FlameWizard_4':'Savage Flame',
  'FlameWizard_5':'Inferno Sphere',
  'FlameWizard_6':'Salamander Mischief',
  'FlameWizard_7':'HEXA Blazing Extinction',
  'FlameWizard_8':'HEXA Orbital Explosion',
  'FlameWizard_9':'HEXA Towering Inferno',
  'Bowmaster_1':'Ascendant Shadow',
  'Bowmaster_10':'Point Zero',
  'Bowmaster_2':'HEXA Hurricane',
  'Bowmaster_3':'Storm of Arrows',
  'Bowmaster_4':'Inhuman Speed',
  'Bowmaster_5':'Quiver Barrage',
  'Bowmaster_6':'Silhouette Mirage',
  'Bowmaster_7':'HEXA Arrow Stream',
  'Bowmaster_8':'HEXA Quiver Cartridge',
  'Bowmaster_9':'HEXA Speed Mirage',
  'Viper_1':'Unleash Neptunus',
  'Viper_10':'Haymaker',
  'Viper_2':'HEXA Octopunch',
  'Viper_3':'Lightning Form',
  'Viper_4':'Lord of the Deep',
  'Viper_5':'Serpent Vortex',
  'Viper_6':'Howling Fist',
  'Viper_7':'HEXA Sea Serpent',
  'Viper_8':'HEXA Serpent Scale',
  'Viper_9':'HEXA Hook Bomber',
  'Cadena_1':'Chain Arts: Grand Arsenal',
  'Cadena_10':'Brutal Ravage',
  'Cadena_2':'HEXA Chain Arts: Thrash',
  'Cadena_3':'Chain Arts: Void Strike',
  'Cadena_4':'Apocalpyse Cannon',
  'Cadena_5':'Chain Arts: Maelstrom',
  'Cadena_6':'Muscle Memory Finale',
  'Cadena_7':'HEXA Muscle Memory',
  'Cadena_8':'HEXA Summon Scimitar',
  'Cadena_9':'HEXA Summon Shotgun',
  'CannonMaster_1':'Super Cannon Explosion',
  'CannonMaster_10':'Barrel of Monkeys',
  'CannonMaster_2':'HEXA Cannon Barrage',
  'CannonMaster_3':'Cannon of Mass Destruction',
  'CannonMaster_4':'The Nuclear Option',
  'CannonMaster_5':'Monkey Business',
  'CannonMaster_6':'Poolmaker',
  'CannonMaster_7':'HEXA Cannon Bazooka',
  'CannonMaster_8':'HEXA Rolling Rainbow',
  'CannonMaster_9':'HEXA Monkey Militia',
  'Captain_1':'The Dreadnought',
  'Captain_10':'Firecracker',
  'Captain_2':'HEXA Rapid Fire',
  'Captain_3':'Bullet Barrage',
  'Captain_4':'Target Lock',
  'Captain_5':'Nautilus Assault',
  'Captain_6':'Death Trigger',
  'Captain_7':'HEXA Broadside',
  'Captain_8':'HEXA Brain Scrambler',
  'Captain_9':'HEXA Scurvy Summons',
  'DarkKnight_1':'Dead Space',
  'DarkKnight_10':'Dark Halidom',
  'DarkKnight_2':'HEXA Gungnir\'s Descent',
  'DarkKnight_3':'Spear of Darkness',
  'DarkKnight_4':'Radiant Evil',
  'DarkKnight_5':'Calamitous Cyclone',
  'DarkKnight_6':'Darkness Aura',
  'DarkKnight_7':'HEXA Dark Impale',
  'DarkKnight_8':'HEXA Final Attack',
  'DarkKnight_9':'HEXA Evil Eye Shock',
  'SoulMaster_1':'Astral Blitz',
  'SoulMaster_10':'Totality',
  'SoulMaster_2':'HEXA Luna Divide',
  'SoulMaster_3':'Cosmos',
  'SoulMaster_4':'Rift of Damnation',
  'SoulMaster_5':'Soul Eclipse',
  'SoulMaster_6':'Flare Slash',
  'SoulMaster_7':'HEXA Cosmic Shower',
  'SoulMaster_8':'HEXA Cosmic Burst',
  'SoulMaster_9':'HEXA Equinox Slash',
  'DemonAvenger_1':'Requiem',
  'DemonAvenger_10':'Rageborne Daredevil',
  'DemonAvenger_2':'HEXA Nether Shield',
  'DemonAvenger_3':'Demonic Frenzy',
  'DemonAvenger_4':'Demonic Blast',
  'DemonAvenger_5':'Dimensional Sword',
  'DemonAvenger_6':'Revenant',
  'DemonAvenger_7':'HEXA Exceed: Execution',
  'DemonAvenger_8':'HEXA Exceed: Lunar Slash',
  'DemonAvenger_9':'HEXA Thousand Swords',
  'DemonSlayer_1':'Nightmare',
  'DemonSlayer_10':'Amethystine Intrusion',
  'DemonSlayer_2':'HEXA Demon Impact',
  'DemonSlayer_3':'Demon Awakening',
  'DemonSlayer_4':'Spirit of Rage',
  'DemonSlayer_5':'Orthrus',
  'DemonSlayer_6':'Demon Bane',
  'DemonSlayer_7':'HEXA Demon Lash',
  'DemonSlayer_8':'HEXA Demon Cry',
  'DemonSlayer_9':'HEXA Cerberus Chomp',
  'DualBlader_1':'Karma Blade',
  'DualBlader_10':'Yamaz Decree',
  'DualBlader_2':'HEXA Phantom Blow',
  'DualBlader_3':'Blade Storm',
  'DualBlader_4':'Blades of Destiny',
  'DualBlader_5':'Blade Tornado',
  'DualBlader_6':'Haunted Edge',
  'DualBlader_7':'HEXA Asura\'s Anger',
  'DualBlader_8':'HEXA Blade Clone',
  'DualBlader_9':'HEXA Blade Fury',
  'Evan_1':'Zodiac Burst',
  'Evan_10':'Union Drive',
  'Evan_2':'HEXA Mana Burst',
  'Evan_3':'Elemental Barrage',
  'Evan_4':'Dragon Slam',
  'Evan_5':'Elemental Radiance',
  'Evan_6':'Spiral of Mana',
  'Evan_7':'HEXA Thunder Circle',
  'Evan_8':'HEXA Dragon Dive',
  'Evan_9':'HEXA Wind Circle',
  'Hero_1':'Spirit Calibur',
  'Hero_10':'Silent Cleave',
  'Hero_2':'HEXA Raging Blow',
  'Hero_3':'Burning Soul Blade',
  'Hero_4':'Instinctual Combo',
  'Hero_5':'Worldreaver',
  'Hero_6':'Sword Illusion',
  'Hero_7':'HEXA Rising Rage',
  'Hero_8':'HEXA Beam Blade',
  'Hero_9':'HEXA Final Attack',
  'Hoyeong_1':'Sage: Apothesis',
  'Hoyeong_10':'Heavenly World Swing Spirit',
  'Hoyeong_2':'Universal Harmony',
  'Hoyeong_3':'Sage: Clone Rampage',
  'Hoyeong_4':'Scroll: Tiger of Songyu',
  'Hoyeong_5':'Sage: Wrath of Gods',
  'Hoyeong_6':'Sage: Three Paths Apparition',
  'Hoyeong_7':'HEXA Heaven: Iron Fan Gale',
  'Hoyeong_8':'HEXA Talisman: Clone',
  'Hoyeong_9':'HEXA Scroll: Star Vortex',
  'Illium_1':'Mytocrystal Expanse',
  'Illium_10':'Excidium',
  'Illium_2':'HEXA Radiant Javelin',
  'Illium_3':'Crystal Ignition',
  'Illium_4':'Templar Knight',
  'Illium_5':'Crystalline Spirit',
  'Illium_6':'Crystal Gate',
  'Illium_7':'HEXA Reaction - Destruction',
  'Illium_8':'HEXA Ex',
  'Illium_9':'HEXA Longinus Spear',
  'Kain_1':'Total Annihilation',
  'Kain_10':'[Possess/Execute] Malicious Flicker',
  'Kain_2':'HEXA Falling Dust',
  'Kain_3':'Dragon Burst',
  'Kain_4':'Fatal Blitz',
  'Kain_5':'Thanatos Descent',
  'Kain_6':'Grip of Agony',
  'Kain_7':'HEXA Strike Arrow',
  'Kain_8':'HEXA Dragon Fang',
  'Kain_9':'HEXA Death\'s Blessing',
  'Kaiser_1':'Nova Triumphant',
  'Kaiser_10':'Pyro Instinct',
  'Kaiser_2':'HEXA Gigas Wave',
  'Kaiser_3':'Nova Guardians',
  'Kaiser_4':'Bladefall',
  'Kaiser_5':'Draco Surge',
  'Kaiser_6':'Dragonflare',
  'Kaiser_7':'HEXA Blade Burst',
  'Kaiser_8':'HEXA Inferno Breath',
  'Kaiser_9':'HEXA Wing Beat',
  'Khali_1':'Hex: Sandstorm',
  'Khali_10':'Void Awake',
  'Khali_2':'HEXA Arts: Flurry',
  'Khali_3':'Hex: Pandemonium',
  'Khali_4':'Void Burst',
  'Khali_5':'Arts: Astra',
  'Khali_6':'Resonate: Ultimatum',
  'Khali_7':'HEXA Void Rush',
  'Khali_8':'HEXA Hex: Chakram Sweep',
  'Khali_9':'HEXA Resonate',
  'Kinesis_1':'From Another Realm',
  'Kinesis_10':'Fractal Horizon',
  'Kinesis_2':'HEXA Ultimate - Metal Press',
  'Kinesis_3':'Psychic Tornado',
  'Kinesis_4':'Ultimate - Mind Over Matter',
  'Kinesis_5':'Ultimate - Psychic Shockwave',
  'Kinesis_6':'Law of Gravity',
  'Kinesis_7':'HEXA Psychic Grab',
  'Kinesis_8':'HEXA Ultimate - Trainwreck',
  'Kinesis_9':'HEXA Kinetic Combo',
  'Lara_1':'Universe in Bloom',
  'Lara_10':'Overflow',
  'Lara_2':'HEXA Essence Sprinkle',
  'Lara_3':'Big Stretch',
  'Lara_4':'Land\'s Connection',
  'Lara_5':'Surging Essence',
  'Lara_6':'Winding Mountain Ridge',
  'Lara_7':'HEXA Dragon Vein Eruption',
  'Lara_8':'HEXA Dragon Vein Absorption',
  'Lara_9':'HEXA Wakeup Call',
  'Len_1':'Sky Splitting Azure Dragon Sword: Ascension',
  'Len_10':'Sky Splitting Azure Dragon Sword: Single Falling Plum Blossom, Heavenly Rain Humanity Desolation',
  'Len_2':'HEXA Plum Blossom Sword Fundamental: Relentless Slash',
  'Len_3':'Plum Blossom Sword Ultimate: Plum Tree Aroma',
  'Len_4':'Lost Soul Awakening',
  'Len_5':'Plum Blossom Sword Ultimate: Dance of Annihilation',
  'Len_6':'Lost Soul Sword Ultimate: Soul Blade',
  'Len_7':'HEXA Lost Soul Sword Fundamental: Soul Strike',
  'Len_8':'HEXA Lost Soul Advent',
  'Len_9':'HEXA Plum Blossom Sword 2nd Form: Scattering Plums',
  'Luminous_1':'Harmonic Paradox',
  'Luminous_10':'Lustrous Orb',
  'Luminous_2':'HEXA Ender',
  'Luminous_3':'Gate of Light',
  'Luminous_4':'Aether Conduit',
  'Luminous_5':'Baptism of Light and Darkness',
  'Luminous_6':'Liberation Orb',
  'Luminous_7':'HEXA Reflection',
  'Luminous_8':'HEXA Apocalypse',
  'Luminous_9':'HEXA Twilight Nova',
  'Marksman_1':'Final Aim',
  'Marksman_10':'Fatal Trigger',
  'Marksman_2':'HEXA Snipe',
  'Marksman_3':'Perfect Shot',
  'Marksman_4':'Split Shot',
  'Marksman_5':'Surge Bolt',
  'Marksman_6':'Repeating Crossbow Cartridge',
  'Marksman_7':'HEXA Piercing Arrow',
  'Marksman_8':'HEXA Frostprey',
  'Marksman_9':'HEXA Final Attack',
  'Mechanic_1':'Ground Zero',
  'Mechanic_10':'Metal Armor: Extermination',
  'Mechanic_2':'HEXA Heavy Salvo',
  'Mechanic_3':'Doomsday Device',
  'Mechanic_4':'Mobile Missile Battery',
  'Mechanic_5':'Full Metal Barrage',
  'Mechanic_6':'Mecha Carrier',
  'Mechanic_7':'HEXA Homing Beacon',
  'Mechanic_8':'HEXA Distortion Bomb',
  'Mechanic_9':'HEXA Robo Launcher RM7',
  'Mercedes_1':'Unfading Glory',
  'Mercedes_10':'Elemental Spirit',
  'Mercedes_2':'HEXA Ishtar\'s Ring',
  'Mercedes_3':'Spirit of Elluel',
  'Mercedes_4':'Sylvidia\'s Flight',
  'Mercedes_5':'Irkalla\'s Wrath',
  'Mercedes_6':'Royal Knights',
  'Mercedes_7':'HEXA Wrath of Enlil',
  'Mercedes_8':'HEXA Unicorn Spike',
  'Mercedes_9':'HEXA Elemental Knights',
  'Mikhail_1':'Durendal',
  'Mikhail_10':'Knight Immortals',
  'Mikhail_2':'HEXA Radiant Cross',
  'Mikhail_3':'Shield of Light',
  'Mikhail_4':'Sword of Light',
  'Mikhail_5':'Radiant Soul',
  'Mikhail_6':'Light of Courage',
  'Mikhail_7':'HEXA Royal Guard',
  'Mikhail_8':'HEXA Install Shield',
  'Mikhail_9':'HEXA Offensive Defense',
  'NightLord_1':'Life and Death',
  'NightLord_10':'Crucial Assault',
  'NightLord_2':'HEXA Quad Star',
  'NightLord_3':'Throwing Star Barrage',
  'NightLord_4':'Shurrikane',
  'NightLord_5':'Dark Lord\'s Omen',
  'NightLord_6':'Throw Blasting',
  'NightLord_7':'HEXA Assassin\'s Mark',
  'NightLord_8':'HEXA Dark Flare',
  'NightLord_9':'HEXA Sudden Raid',
  'NightWalker_1':'Silence',
  'NightWalker_10':'Stygian Command',
  'NightWalker_2':'HEXA Quintuple Star',
  'NightWalker_3':'Shadow Spear',
  'NightWalker_4':'Greater Dark Servant',
  'NightWalker_5':'Shadow Bite',
  'NightWalker_6':'Rapid Throw',
  'NightWalker_7':'HEXA Shadow Bat',
  'NightWalker_8':'HEXA Dark Omen',
  'NightWalker_9':'HEXA Dominion',
  'Palladin_1':'Sacred Bastion',
  'Palladin_10':'Dominus Obrion',
  'Palladin_2':'HEXA Blast',
  'Palladin_3':'Divine Echo',
  'Palladin_4':'Hammers of the Righteous',
  'Palladin_5':'Grand Guardian',
  'Palladin_6':'Mighty Mjolnir',
  'Palladin_7':'HEXA Divine Charge',
  'Palladin_8':'HEXA Heaven\'s Hammer',
  'Palladin_9':'HEXA Final Attack',
  'PathFinder_1':'Forsaken Relic',
  'PathFinder_10':'Relic Penetration',
  'PathFinder_2':'HEXA Cardinal Burst',
  'PathFinder_3':'Nova Blast',
  'PathFinder_4':'Raven Tempest/Fury of the Wild Tempest',
  'PathFinder_5':'Obsidian Barrier',
  'PathFinder_6':'Relic Unbound',
  'PathFinder_7':'HEXA Cardinal Deluge',
  'PathFinder_8':'HEXA Cardinal Torrent',
  'PathFinder_9':'HEXA Shadow Raven',
  'Phantom_1':'Defying Fate',
  'Phantom_10':'Moonlit Serenade',
  'Phantom_2':'HEXA Tempest',
  'Phantom_3':'Luck of the Draw',
  'Phantom_4':'Ace in the Hole',
  'Phantom_5':'Phantom\'s Mark',
  'Phantom_6':'Rift Break',
  'Phantom_7':'HEXA Mille Aiguilles',
  'Phantom_8':'HEXA Carte Noir',
  'Phantom_9':'HEXA Rose Carte Finale',
  'Eunwol_1':'Advent of the Fox',
  'Eunwol_10':'Eternal Transcendence',
  'Eunwol_2':'HEXA Spirit Claw',
  'Eunwol_3':'Fox God Flash',
  'Eunwol_4':'Spiritgate',
  'Eunwol_5':'True Spirit Claw',
  'Eunwol_6':'Smashing Multipunch',
  'Eunwol_7':'HEXA Fox Spirits',
  'Eunwol_8':'HEXA Bomb Punch',
  'Eunwol_9':'HEXA Spirit Frenzy',
  'Shadower_1':'Halve Cut',
  'Shadower_10':'Authentic Darkness',
  'Shadower_2':'HEXA Assassinate',
  'Shadower_3':'Shadow Assault',
  'Shadower_4':'Trickblade',
  'Shadower_5':'Sonic Blow',
  'Shadower_6':'Slash Shadow Formation',
  'Shadower_7':'HEXA Meso Explosion',
  'Shadower_8':'HEXA Dark Flare',
  'Shadower_9':'HEXA Sudden Raid',
  'Striker_1':'Thunder Wall Sea Wave',
  'Striker_10':'Flash Storm Annihilation',
  'Striker_2':'HEXA Annihilate',
  'Striker_3':'Lightning Cascade',
  'Striker_4':'Shark Torpedo',
  'Striker_5':'Lightning God Spear Strike',
  'Striker_6':'Lightning Spear Multistrike',
  'Striker_7':'HEXA Thunderbolt',
  'Striker_8':'HEXA Typhoon',
  'Striker_9':'HEXA Sea Wave',
  'WildHunter_1':'Nature\'s Truth',
  'WildHunter_10':'Gear Storm',
  'WildHunter_2':'Wild Vulcan: Apex VI',
  'WildHunter_3':'Command: Predator\'s Eye',
  'WildHunter_4':'Overbite',
  'WildHunter_5':'Primal Bloom',
  'WildHunter_6':'Wild Vulcan: Overdrive',
  'WildHunter_7':'Assist VI',
  'WildHunter_8':'Command VI',
  'WildHunter_9':'Another Bite / Final Attack / Trap Seeder VI',
  'WindBreaker_1':'Mistral Spring',
  'WindBreaker_10':'Element Tempest',
  'WindBreaker_2':'HEXA Song of Heaven',
  'WindBreaker_3':'Howling Gale',
  'WindBreaker_4':'Merciless Winds',
  'WindBreaker_5':'Gale Barrier',
  'WindBreaker_6':'Vortex Sphere',
  'WindBreaker_7':'HEXA Trifling Wind',
  'WindBreaker_8':'HEXA Fairy Spiral',
  'WindBreaker_9':'HEXA Storm Whim',
  'Xenon_1':'Artificial Evolution',
  'Xenon_10':'Neoteric Trice',
  'Xenon_2':'HEXA Mecha Purge: Snipe',
  'Xenon_3':'Omega Blaster',
  'Xenon_4':'Core Overload',
  'Xenon_5':'Hypogram Field: Fusion',
  'Xenon_6':'Photon Ray',
  'Xenon_7':'HEXA Hypogram Field: Penetrate',
  'Xenon_8':'HEXA Salvo System',
  'Xenon_9':'HEXA Beam Dance',
  'Zero_1':'End Time',
  'Zero_10':'Bitemporis',
  'Zero_2':'Time Piece',
  'Zero_3':'Chrono Break',
  'Zero_4':'Twin Blades of Time',
  'Zero_5':'Shadow Flash',
  'Zero_6':'Ego Weapon',
  'Zero_7':'HEXA Spin Driver',
  'Zero_8':'HEXA Flash Assault',
  'Zero_9':'HEXA Moon Strike'
};
